# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.IntegerField()),
                ('text_massage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Massages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.IntegerField()),
                ('text_massage', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='answer_massage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot.Massages'),
        ),
    ]
