# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot', '0002_auto_20161027_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='massages',
            name='author_name',
        ),
    ]
