# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot', '0003_auto_20161027_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='massages',
            old_name='author_id',
            new_name='author',
        ),
    ]
