# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot', '0004_auto_20161027_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='answer_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enot.Comments'),
        ),
    ]
