# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot', '0006_auto_20161027_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='answer_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enot.Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enot.Massages'),
        ),
    ]
