# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot', '0007_auto_20161027_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='massages',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
