# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot', '0008_massages_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='massages',
            name='imag',
        ),
        migrations.AddField(
            model_name='imag',
            name='img_massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enot.Massages'),
        ),
    ]
